name: flutter_template
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 # https://pub.dev/packages/dio
  dio: ^5.4.0
  flutter_localizations:
    sdk: flutter
  # # https://pub.dev/packages/firebase_analytics
  # firebase_analytics: ^10.8.0
  # # https://pub.dev/packages/firebase_core
  # firebase_core: ^2.24.2
  # # https://pub.dev/packages/firebase_remote_config
  # firebase_remote_config: ^4.3.8
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.3
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.1
  # https://pub.dev/packages/get_it
  get_it: ^7.6.6
  # https://pub.dev/packages/go_router
  go_router: ^13.0.1
  # https://pub.dev/packages/intl
  intl: ^0.18.1
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.1
  # https://pub.dev/packages/logger
  logger: ^2.0.2+1
  # https://pub.dev/packages/sentry_flutter
  sentry_flutter: ^7.14.0
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.8
  # https://pub.dev/packages/flutter_gen_runner
  flutter_gen_runner: ^5.4.0
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^3.0.1
  # https://pub.dev/packages/freezed
  freezed: ^2.4.6
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/